export const REQUEST_HELLO_WORLD = 'REQUEST_HELLO_WORLD';
export const RECEIVE_HELLO_WORLD = 'RECEIVE_HELLO_WORLD';

export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const START_WEATHER_STREAM = 'START_WEATHER_STREAM';

export const SWITCH_THEME = 'SWITCH_THEME';

export const SET_VOICE_COMMAND = 'SET_VOICE_COMMAND';
